spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wx-portal?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

debug: true